PUT http://localhost:4000/materias/updateMateria
content-type: application/json

{
    "nombre": "Matematicas",
    "horas": "5", 
    "docente": "Martin", 
    "dia": "Lunes",
    "id":"1"
}